server:
  port: ${port:8022}

security:
  jwt:
    key-store: classpath:JWTKeystore.p12
    key-store-password: devdcorespass
    key-pair-alias: jwt-key
    key-pair-password: devdcorespass
    public-key: classpath:jwt-signing-public-key.txt


spring:
  application:
    name: auth-service

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

  flyway:
    table: account_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userservicedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
#    url: jdbc:mysql://bookstore.ccz3nxew3wxs.ap-southeast-1.rds.amazonaws.com:3306/userservicedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: admin
#    password: jerrytran97
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.bookstore.*: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, prometheus

  security:
    enabled: false