version: '3'
services:
  ## Prometheus
  elasticsearch:
    container_name: product-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    volumes:
      - /Users/phuctran/Documents/datn/bookstore-microservice/search-service/data

  kibana:
    container_name: product-kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      -  '9411:9411'

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - 2181:2181
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
#    ports:
#      - '9092:9092'
