-- CREATE USER TABLE
CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE ,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX USER_ID_INDEX ON users (user_id);

-- CREATE ROLE TABLE
CREATE TABLE IF NOT EXISTS roles (
    role_id VARCHAR(255) NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255),
    ROLE_NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
    );
CREATE UNIQUE INDEX ROLE_ID_INDEX ON roles (role_id);

-- CREATE USER-ROLES MAPPING TABLE
CREATE TABLE IF NOT EXISTS user_roles (
    USER_ID VARCHAR(255) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES users (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES roles (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
    );
CREATE INDEX USER_FK_INDEX ON USER_ROLES (user_id);
CREATE INDEX ROLE_FK_INDEX ON USER_ROLES (role_id);

-- CREATE OAUTH_CLIENT_DETAILS TABLE
CREATE TABLE IF NOT EXISTS oauth_client_details (
    CLIENT_ID VARCHAR(255) PRIMARY KEY,
    RESOURCE_IDS VARCHAR(255),
    CLIENT_SECRET VARCHAR(255),
    SCOPE VARCHAR(255),
    AUTHORIZED_GRANT_TYPES VARCHAR(255),
    WEB_SERVER_REDIRECT_URI VARCHAR(255),
    AUTHORITIES VARCHAR(255),
    ACCESS_TOKEN_VALIDITY INTEGER,
    REFRESH_TOKEN_VALIDITY INTEGER,
    ADDITIONAL_INFORMATION VARCHAR(4096),
    AUTOAPPROVE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);